### *Importing NumPy package*

In [63]:
import numpy as np
print("NumPy Version: " + np.__version__)

NumPy Version: 1.19.5


### Creating 1-dimensional Array

In [64]:
ar1 = np.array([5,7,2])
print(ar1)

[5 7 2]


### Creating 2-dimensional Array

In [65]:
ar2 = np.array([[5,7,2],
                [2,3,9]])
print(ar2)

[[5 7 2]
 [2 3 9]]


### Creating 3-dimensional Array

In [66]:
ar3 = np.array([[[5,7,2],
                [2,3,9]],
               [[3,5,9],
                [6,2,7]]])
print(ar3)

[[[5 7 2]
  [2 3 9]]

 [[3 5 9]
  [6 2 7]]]


## Avoiding Conflicts with Global Namespace

In [67]:
np.max(ar3)

9

In [68]:
max([2,5,4])

5